djangodelights/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inventory/', include('django.contrib.auth.urls')),
    path('', include('inventory.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

inventory/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    # path("/ingredients", views.IngredientList.as_view(), name="ingredients"),
    path('ingredients', views.ingredients, name='ingredients'),
    path('menu', views.menu, name='menu'),
    path('purchases', views.purchases, name='purchases'),
    path('create_purchase/', views.create_purchase, name="create_purchase"),
    path('create_ingredient', views.IngredientCreateView.as_view(), name="create_ingredient"),
    path('create_menuitem', views.MenuItemCreateView.as_view(), name="create_menuitem"),
    path('create_reciperequirement', views.RecipeRequirementCreateView.as_view(), name="create_reciperequirement"),
    path('incomereport', views.incomereport, name='incomereport'),
    path('modify_ingredient/<int:id>/', views.modify_ingredient, name='modify_ingredient'),
    path('delete_ingredient/<int:id>/', views.delete_ingredient, name='delete_ingredient'),
    path('signup', views.SignupView.as_view(), name='signup'),
    path('login_page', views.login_page, name='login_page'),
    path('logout', views.logout_user, name='logout'),
    
]

inventory/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.signals import post_save


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date_modified = models.DateTimeField(User, auto_now=True)
    phone = models.CharField(max_length=25, blank=True, null=True)
    address1 = models.CharField(max_length=200, blank=True, null=True)
    address2 = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.user.username
    
def create_profile(sender, instance, created, **kwargs):
    if created:
        user_profile = Profile(user=instance)
        user_profile.save()

post_save.connect(create_profile, sender=User)

# Create your models here.
class Ingredient(models.Model):
    name = models.CharField(max_length=25, null=False, blank=False)
    quantity = models.DecimalField(max_digits=10, decimal_places=2, null=False, blank=False)
    unit = models.CharField(max_length=10, null=False, blank=False)
    unit_price = models.DecimalField(max_digits=10, decimal_places=2, null=False, blank=False)

    def __str__(self):
        return self.name


class MenuItem(models.Model):
    name = models.CharField(max_length=25, null=False, blank=False)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=False, blank=False)
    ingredients = models.ManyToManyField(Ingredient, through='RecipeRequirement')

    def __str__(self):
        return self.name


class RecipeRequirement(models.Model):
    item = models.ForeignKey(MenuItem, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    quantity = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return f'{self.item} - {self.ingredient}'

class Purchase(models.Model):
    menu_item = models.ForeignKey(MenuItem, on_delete=models.CASCADE)
    purchase_date = models.DateTimeField(auto_now_add=True, null=False, blank=False)
    quantity = models.IntegerField(blank=True, null=True)
    total = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, default=0)
    cogs = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, default=0)

    def __str__(self):
        return self.menu_item.name
    





    
        

inventory/forms.py
from .models import *
from django.forms import ModelForm


class AddPurchaseForm(ModelForm):
    class Meta:
        model = Purchase 
        fields = ['menu_item', 'quantity']

class CreateIngredientForm(ModelForm):
    class Meta:
        model = Ingredient
        fields = '__all__'

class CreateMenuItemForm(ModelForm):
    class Meta:
        model = MenuItem
        fields = '__all__'

class CreateRecipeRequirementForm(ModelForm):
    class Meta:
        model = RecipeRequirement
        fields = '__all__'

inventory/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.forms import modelformset_factory
from django.contrib.auth.forms import UserCreationForm

from .models import *
from .forms import AddPurchaseForm, CreateIngredientForm, CreateMenuItemForm, CreateRecipeRequirementForm


# Create your views here.

class SignupView(CreateView):
    template_name = 'inventory/signup.html'
    form_class = UserCreationForm

    def get_success_url(self):
        return reverse('login_page')
    




def login_page(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
        return redirect('home')

    return render(request, 'inventory/login_page.html', {})


def logout_user(request):
    
    logout(request)
    return redirect('home')




def home(request):
    # return HttpResponse("Hello world")
    return render(request, "inventory/home.html")

@login_required(login_url='/login_page')
def ingredients(request):
    ingred_list = Ingredient.objects.all().order_by('name')
    return render(request, "inventory/ingredient_list.html", {'ingredients': ingred_list})





@login_required(login_url='/login_page')
def modify_ingredient(request, id):
    ingredient = Ingredient.objects.get(pk=id)
    
    if request.method == 'POST':
        form = CreateIngredientForm(request.POST, instance=ingredient)
        if form.is_valid():
            form.save()
        return redirect('ingredients')
    else:
        form = CreateIngredientForm(instance=ingredient)
        context = {'form': form,
                   'ingredient': ingredient}
        return render(request, 'inventory/modify_ingredient.html', context)

@login_required(login_url='/login_page')
def delete_ingredient(request, id):
    
    ingredient = Ingredient.objects.get(pk=id)
    ingredient.delete()
    return redirect('ingredients')
    
@login_required(login_url='/login_page')
def menu(request):
    menu_items = MenuItem.objects.all()
    recipe_requirements = RecipeRequirement.objects.all()
    ingredients = Ingredient.objects.all()


    context = {
        'menu_items': menu_items,
        'recipe_requirements': recipe_requirements,
        'ingredients': ingredients
    }
    return render(request, "inventory/menu.html", context)

@login_required(login_url='/login_page')
def purchases(request):
    purchases = Purchase.objects.all()
    context = {'purchases':purchases}

    return render(request, 'inventory/purchases.html', context)


@login_required(login_url='/login_page')
def create_purchase(request):
    form = AddPurchaseForm(request.POST)
    if request.method == 'POST':
        if form.is_valid:
            create_purchase = form.save()
            create_purchase.total = create_purchase.quantity * create_purchase.menu_item.price
            create_purchase.save()

            menu_item_id = request.POST.get('menu_item')
            quantity = int(request.POST.get('quantity'))
            menu_item = MenuItem.objects.get(pk=menu_item_id)
            
            cogs = calculate_cogs(menu_item, quantity)
            create_purchase.cogs = cogs
            create_purchase.save()

            quantitypurchased = create_purchase.quantity
            # Change the ingredient inventory
            for requirement in menu_item.ingredients.through.objects.filter(item=menu_item):
                ingredient = requirement.ingredient
                quantityofingredientrequired = requirement.quantity
                ingredient.quantity -= quantityofingredientrequired * quantitypurchased
                ingredient.save()

            messages.success(request, "Purchase added...")
            return redirect('purchases')
    context = {'form': form,}
    return render(request, 'inventory/create_purchase.html', context)

def calculate_cogs(menu_item, quantity):
    cogsperingredient = 0
    for requirement in menu_item.ingredients.through.objects.filter(item=menu_item):
        ingredient = requirement.ingredient
        quantityofingredientrequired = requirement.quantity
        unitpriceofingredient = ingredient.unit_price
        cogsperingredient += quantityofingredientrequired * unitpriceofingredient
    cogs = cogsperingredient * quantity
    return cogs

@login_required(login_url='/login_page')
def incomereport(request):
    purchases = Purchase.objects.all()
    revtotal = 0
    expensetotal = 0
    for purchase in purchases:
        revtotal += purchase.total
        expensetotal += purchase.cogs
    overalltotal = revtotal - expensetotal

    context = {'purchases': purchases,
               'revtotal': revtotal,
               'expensetotal': expensetotal,
               'overalltotal': overalltotal
               }

    return render(request, 'inventory/incomereport.html', context)


class IngredientCreateView(LoginRequiredMixin, CreateView):
    model = Ingredient
    form_class = CreateIngredientForm
    template_name = 'inventory/create_ingredient.html'
    success_url = 'ingredients'


class MenuItemCreateView(LoginRequiredMixin, CreateView):
    model = MenuItem
    form_class = CreateMenuItemForm
    template_name = 'inventory/create_menuitem.html'
    success_url = 'menu'


class RecipeRequirementCreateView(LoginRequiredMixin, CreateView):
    model = RecipeRequirement
    form_class = CreateRecipeRequirementForm
    template_name = 'inventory/create_reciperequirement.html'
    success_url = 'menu'

inventory/templates/inventory/base.html
<!DOCTYPE html>
<html>

{% block head %}
<head>
{% load static %}
<title>{% block title %}Inventory{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
{% endblock %}
<body>
    

        <nav class="navbar navbar-expand navbar-dark bg-success bg-gradient">
            
                <a href="{% url 'home' %}" class="navbar-brand">Django Delights</a>
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ingredients' %}">Ingredients</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'menu' %}">Menu</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'purchases' %}">Purchases</a>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login_page' %}">Login</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'signup' %}">Register</a>
                    </li>
                </ul>
            
        </nav>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
{% block content %}
{% endblock %}
</body>
</html>

inventory/templates/inventory/create_ingredient.html
{% extends './base.html' %}

{% block title %}Create Ingredient{% endblock %}
{% block content %}
<h2>Create an Ingredient</h2>
<form method="POST">
{% csrf_token %}
{{ form.as_p }}

<button type="submit">Submit</button>
</form>
<br>
<a href="{% url 'ingredients' %}">Back to Ingredients</a>

{% endblock %}

inventory/templates/inventory/create_menuitem.html
{% extends './base.html' %}
{% block title %}Create a Menu Item{% endblock %}
{% block content %}

<h2>Create a New Menu Item</h2>
<form method="POST">
    {% csrf_token %}

    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
<br>
<a href="{% url 'menu' %}">Back to Menu</a>

{% endblock %}

inventory/templates/inventory/create_purchase.html
{% extends './base.html' %}

{% block content %}

<h1>Create a Purchase</h1>
<br>

<form method="POST" action="{% url 'create_purchase' %}">
    {% csrf_token %}

    {{ form.as_p }}


    <br>
        <button type="submit" class="btn">Add to Purchase</button>
            <a href="{% url 'menu' %}">Back to Menu</a>



</form>



{% endblock %}

inventory/templates/inventory/create_reciperequirement.html
{% extends './base.html' %}
{% load static %}
{% block content %}

<form method="POST">
    {% csrf_token %}
    <h2>Create a new ingredient requirement for a menu item</h2>
    {{ form.as_p }}

    <button type="submit">Submit</button>

</form> 
<br>
<hr>
<br>
<a href="{% url 'menu' %}">Back to Menu</a>


{% endblock %}

inventory/templates/inventory/home.html
<!DOCTYPE html>
<html>
{% extends './base.html' %}
{% load static %}

{% block content %}
<body>
    
<!-- Banner -->
<div class="banner">
    <h2>Eddie Mapes</h2>
    <h1>Django Delights</h1>
</div>  

<!-- Content section including picture w/ caption   -->

<div class="content">
    <div class="first photo">
        <div class="image-container">
            <img src="{% static '/css/img/foods.jpg' %}">
        </div>
        <span class="caption">"Only the finest ingredients are used" -The Chef</span>
    </div>





</div>



    
</body>
{% endblock %}

</html>

inventory/templates/inventory/incomereport.html
{% extends './base.html' %}

{% block content %}
<table>
    <tr>
    <th>Menu Items</th>
    <th>Quantity</th>
    <th>Revenue</th>
    <th>Expenses</th>
    <th></th>
    </tr>
    {% for purchase in purchases %}
    <tr>
        <td>{{purchase.menu_item}}</td>
        <td>{{purchase.quantity}}</td>
        <td>${{purchase.total}}</td>
        <td>${{purchase.cogs}}</td>
        <td></td>
    </tr>
    {% endfor %}
    <tr>
        <td></td>
        <td>Total:</td>
        <td>${{ revtotal }}</td>
        <td>${{ expensetotal }}</td>
        <td>${{ overalltotal }}</td>
    </tr>

</table>


{% endblock %}

inventory/templates/inventory/ingredient_list.html
{% extends './base.html' %}
{% block title %}Our Ingredients{% endblock %}

{% block content %}
<h1 style="text-align: center;">Ingredients</h1>
<hr>
<div class="ingredient-div">
<table class="ingredient-table">
    <th class="ingredient-th">Ingredient</th>
    <th class="ingredient-th">Quantity</th>
    <th class="ingredient-th">Unit Price</th>
    <th class="ingredient-th">Modify</th>
    {% for i in ingredients %}
    
        <tr>
          <td class="ingredient-td">{{ i.name }}</td>
          <td class="ingredient-td">{{ i.quantity }} {{ i.unit }}</td>
          <td class="ingredient-td">${{ i.unit_price }}</td>
          <td class="ingredient-td"><a href="{% url 'modify_ingredient' i.id %}">Update</a></td>
        </tr>
{% endfor %}
</table>
</div>
<br>
<a href="{% url 'create_ingredient' %}">Create an ingredient</a>
{% endblock %}

inventory/templates/inventory/login_page.html
{% extends './base.html' %}
{% block content %}
<form method="POST">
{% csrf_token %}

<input type="text" name="username" placeholder="Username">
<br><br><br>
<input type="text" name="password" placeholder="Password">
<br><br><br><br><br>

<input type="submit" class="button" value="Login" name="Login">
</form>





{% endblock %}

inventory/templates/inventory/menu.html
{% extends './base.html' %}
{% block title %}Our Menu{% endblock %}
{% block content %}
<h1 style="text-align: center;">Menu</h1>
<hr>

<form method="POST">
    {% csrf_token %}
<div class="ingredient-div">
    <table class="ingredient-table">
    <tr>
        <th class="ingredient-th">Item</th>
        <th class="ingredient-th">Price</th>
        <th class="ingredient-th">Ingredients</th>
    </tr>
    {% for menu_item in menu_items %}
    <tr>
        <td class="ingredient-td">{{ menu_item.name }}</td>
        <td class="ingredient-td">${{ menu_item.price }}</td>
        <td class="ingredient-td">
                {% for requirement in menu_item.reciperequirement_set.all %}
                <p>{{ requirement.ingredient.name }} - {{ requirement.quantity }}</p>
                {% endfor %}
        </td>
        
    </tr>
    
    {% endfor %}
    
</table>
</div>

</form>


<br>
<a href="{% url 'create_menuitem' %}">Create a menu item</a>
<br>
<a href="{% url 'create_reciperequirement' %}">Add a requirement for a menu item</a>
<br>
<a href="{% url 'create_purchase' %}">Add items to purchase</a>


{% endblock %}

inventory/templates/inventory/modify_ingredient.html
{% extends './base.html' %}
{% block title %}Modify Ingredient Inventory{% endblock %}

{% block content %}

<form method="POST">
{% csrf_token %}
{{ form.as_p }}

<input type="submit" value="Submit">
</form>
<br>
<a href="{% url 'delete_ingredient' id=ingredient.id %}"><button type=button>Delete</button></a>
{% endblock %}

inventory/templates/inventory/purchases.html
{% extends './base.html' %}

{% block content %}
<h1 style="text-align: center;">Purchases</h1>
<hr>
<table class="ingredient-table">
<th class="ingredient-th">Menu Item</th>
<th class="ingredient-th">Quantity</th>
<th class="ingredient-th">Date</th>
<th class="ingredient-th">Total</th>
{% for p in purchases %}
<tr>
    <td class="ingredient-td">{{p.menu_item}}</td>
    <td class="ingredient-td">{{p.quantity}}</td>
    <td class="ingredient-td">{{p.purchase_date}}</td>
    <td class="ingredient-td">${{p.total}}</td>
</tr>

{% endfor %}

</table>
<hr>
<a href="{% url 'incomereport' %}">Calculate profit/loss</a>

{% endblock %}

inventory/templates/inventory/signup.html
{% extends './base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Signup</button>
</form>

{% endblock %}

inventory/templates/inventory/test.html
<!DOCTYPE html>
{% extends './base.html' %}
{% load static %}


{% block content %}

<body><h1>Testing part of app</h1></body>
<br>
<a href="{% url 'home' %}">Home</a>
<table class="ingredient-table">
    <tr>
        <th class="ingredient-th">num1</th>
        <th class="ingredient-th">string1</th>
    </tr>

    <form method="POST">
        {% csrf_token %}
        <tr>
        {% for field in testform %}
        
        <td class="ingredient-td">{{ field }}</td>

        {% endfor %}
    </tr>
        <button type="submit">Submit</button>
    </form>
</table>



{% endblock %}